- id: '1776032988102'
  alias: Deck Motion Light Scene Control
  description: Use Hue scenes for deck lighting on motion
  triggers:
  - entity_id:
    - binary_sensor.deck_motion_sensor_motion
    to: 'on'
    trigger: state
  conditions:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: sun
        after: sunset
        after_offset: 00:20:00
  actions:
  - target:
      entity_id: scene.deck_motion_white
    action: scene.turn_on
  - wait_for_trigger:
    - entity_id:
      - binary_sensor.deck_motion_sensor_motion
      to: 'off'
      trigger: state
    continue_on_timeout: false
  - delay: 00:02:00
  - target:
      entity_id: scene.deck_red_night
    action: scene.turn_on
  mode: restart
- id: '1776033061008'
  alias: Front Door Motion Lighting
  description: Turn Front Door light to 100% on motion, fade to 20% after 2 min of
    no motion
  triggers:
  - entity_id: binary_sensor.front_door_motion_detector
    to: 'on'
    trigger: state
  conditions:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: sun
        after: sunset
        after_offset: 00:10:00
    - condition: and
      conditions:
      - condition: time
        after: 05:00:00
      - condition: sun
        before: sunrise
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.front_door_motion_detector
        state: 'on'
      sequence:
      - target:
          entity_id: light.front_door
        data:
          brightness_pct: 100
          transition: 2
        action: light.turn_on
  mode: restart
- id: '1776033122398'
  alias: Lamp Post Off at Midnight
  description: ''
  triggers:
  - at: 00:00:00
    trigger: time
  conditions: []
  actions:
  - target:
      entity_id: light.lamp_post
    action: light.turn_off
  mode: single
- id: '1776033124647'
  alias: Lamp Post Off at Midnight
  description: ''
  triggers:
  - at: 00:00:00
    trigger: time
  conditions: []
  actions:
  - target:
      entity_id: light.lamp_post
    action: light.turn_off
  mode: single
- id: '1776033162221'
  alias: Lights off at Dawn
  description: ''
  triggers:
  - event: sunrise
    trigger: sun
  conditions: []
  actions:
  - target:
      entity_id:
      - light.driveway
      - light.front_door
      - light.hue_color_lamp_16
    action: light.turn_off
    data: {}
  mode: single
- id: '1776033197114'
  alias: Outdoor Lights On After Sunset
  description: ''
  triggers:
  - event: sunset
    offset: 00:20:00
    trigger: sun
  conditions: []
  actions:
  - target:
      entity_id:
      - light.lamp_post
      - light.driveway
      - light.front_door
    action: light.turn_on
    data:
      brightness_pct: 20
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.deck_red_night
  mode: single
- id: '1776033248422'
  alias: Reset Front door lamp when Motion clears
  description: Set Front Door light fade to 20% after 2 min of no motion
  triggers:
  - entity_id:
    - binary_sensor.front_door_motion_detector
    to: 'off'
    trigger: state
    for:
      hours: 0
      minutes: 2
      seconds: 0
  conditions:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: sun
        after: sunset
        after_offset: 00:20:00
    - condition: sun
      before: sunrise
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 20
      transition: 5
    target:
      device_id: 7d0be17758df36232b54ec19129a15bf
  mode: restart
